### ISSUE TITLE
Broken Icons

### ISSUE THREAD

**Issue by L0n0n0k** [baitmooth/snow#20]
```
paste what turtl copied to the clipboard here
Don't add a .zip
```

<item component="ComponentInfo{org.briarproject.briar.android/org.briarproject.briar.android.splash.SplashScreenActivity}" drawable="briar"/>

<item component="ComponentInfo{com.duolingo/com.duolingo.app.LoginActivity}" drawable="duolingo"/>

**Comment by baitmooth** [comment]
… working on it
