### ISSUE TITLE
Porting Scripts from Arcticons

### ISSUE THREAD

**Issue by Kaiserdragon2** [baitmooth/snow#27]
In the Arcticons script it checks the icons for linewidth linejoin and lineend and color. What are the requirements here?

- color white
- only file?

**Comment by baitmooth** [comment]
I usually dont use strokes, but for the sake of consistency it should check those too. I found many icons in the existing set that are kinda messy because of missing checks, so yes lets do it.

**Comment by baitmooth** [comment]
Could you make a routine to update the **CHANGELOG.md** into **app/src/main/res/values/cangelog.xml**

**Comment by baitmooth** [comment]
And I there is another question:
There was this helper script (scour.sh) to remove inkscapes annotations from the svg. how is this done now?

**Comment by Kaiserdragon2** [comment]
> Could you make a routine to update the **CHANGELOG.md** into **app/src/main/res/values/cangelog.xml** (as part of preparerelease)?

Yes that should be possible

**Comment by Kaiserdragon2** [comment]
> And I have another question:
> There was this helper script (scour.sh) to remove inkscapes annotations from the svg. how is this done now?

At arcticons there isn't any script to remove inkscape annotations because donnno does it when i review the svgs. I would be possible to use scour in the script, but i would recommend when reviewing just saving them as plain svg.
